# Generated by Django 3.1.1 on 2020-09-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, default=None, max_length=50, unique=True),
        ),
    ]
