# Generated by Django 3.1.1 on 2020-09-20 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_doi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='article',
            name='references',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=50)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
                ('references', models.ManyToManyField(related_name='referenced_by', to='main.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default=None)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
            ],
        ),
    ]
