# Generated by Django 3.1.1 on 2020-09-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200920_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=50)),
                ('abstract', models.TextField(blank=True, default=None)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
                ('references', models.ManyToManyField(related_name='referenced_by', to='main.Article')),
            ],
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='article',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='references',
        ),
        migrations.DeleteModel(
            name='Abstract',
        ),
        migrations.DeleteModel(
            name='Metadata',
        ),
    ]
