# Generated by Django 3.1.1 on 2020-09-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='ip_address',
            field=models.GenericIPAddressField(default=None),
        ),
        migrations.AddField(
            model_name='proxy',
            name='port',
            field=models.IntegerField(default=None),
        ),
    ]
