# Generated by Django 3.1.1 on 2020-09-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0002_auto_20200916_1547'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proxy',
            unique_together={('ip_address', 'port')},
        ),
    ]
