# Generated by Django 3.1.1 on 2020-09-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0003_auto_20200916_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='conn_succ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proxy',
            name='conn_total',
            field=models.IntegerField(default=0),
        ),
    ]
